[FEAT]:cards_section : Added the cards
tcet-opensource/resume-screener-frontend pull request #8
Opened 2023-06-19 17:36 UTC by shlok-2003

Added Card Section resolving issue no #7 

DIsclamer: The background image has not been added, since the component was divided for two issues

2023-06-20 10:58 UTC, JayeshVP24 requested changes

2023-06-20 10:58 UTC, JayeshVP24 commented on src/components/CardSection/index.astro
> +<section class="px-16 my-5 grid grid-cols-1 sm:grid-cols-4 lg:grid-cols-3 gap-16">
change gap
make gap smaller for mobile and larger for desktop

2023-06-20 10:58 UTC, JayeshVP24 commented on src/components/CardSection/index.astro
> +<section class="px-16 my-5 grid grid-cols-1 sm:grid-cols-4 lg:grid-cols-3 gap-16">
make padding px-4 for mobile px-16 for larger screens

2023-06-20 10:58 UTC, JayeshVP24 commented on src/components/CardSection/index.astro
> +                    <p class="font-sans font-normal text-gray-300 text-sm sm:text-base">{item.cardText}</p>
add little padding top

2023-06-20 16:06 UTC, JayeshVP24 commented on src/components/CardSection/index.astro
>                      <p class="font-sans font-normal text-gray-300 text-sm sm:text-base">{item.cardText}</p>
add little padding above item.cardText not above item.cardTitle

2023-06-20 18:43 UTC, shlok-2003 commented
Made the corresponding changes in the file,

2023-06-20 19:16 UTC, JayeshVP24 commented on src/components/CardSection/index.astro
> +<section class="my-5 grid grid-cols-1 sm:grid-cols-4 lg:grid-cols-3 px-4 sm:px-8 md:px-12 lg:px-16 gap-8 sm:gap-10 md:gap-14 lg:gap-16">
remove grid, change to `flex flex-wrap`

2023-06-21 16:14 UTC, JayeshVP24 approved these changes
LGTM

2023-06-21 16:14 UTC, merged